##############################
# Country definition for U02 #
##############################

#####################
# Country main data #
#####################

country = {
  tag                = U02
  regular_id         = IND
  puppet             = ENG
  ai_settings        = { flags = { MOB1 = yes MOB2 = yes } }
  capital            = 1459 # Delhi
  dissent            = 9
  manpower           = 489
  # Resource Reserves
  energy         = 5520
  metal          = 2760
  rare_materials = 1380
  oil            = 500
  supplies       = 500
  money          = 70
  transports     = 200
  escorts        = 20

  diplomacy = {
    relation = { tag = ENG value = 50 access = yes }
  }
  SpyInfo                = { country = "U02" NumberOfSpies = 3 }

  nationalprovinces      = { 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458 1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 1278 1529 1533 1534 1537 1538 1539 1540 1612 }
  ownedprovinces         = { 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458 1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 1278 1529 1533 1534 1537 1538 1539 1540 1612 }
  controlledprovinces    = { 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1421 1439 1440 1441 1442 1443 1445 1450 1455 1458 1444 1446 1447 1448 1449 1451 1452 1453 1454 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1512 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1530 1531 1532 1535 1536 1278 1529 1533 1534 1537 1538 1539 1540 1612 }

  techapps               = { 1010 1020 1030 1040 1050 1060 1160 1170 1180 1190 1200 1210 1220 1230 1240 1910 1920 1930 1940 1950 1960 1970 1980 13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1396 2860 2870 2880 2020 2290 2300 2310 7600 7610 2620 2010 1830 1840 1850 1860 2800 2450 3010 3020 3030 3040 3110 3120 3130 3140 3210 3220 3230 4500 4510 4520 4530 4540 4550 4010 4600 4610 4620 4630 4120 5310 54010 54020 54030 5316 5326 5810 5820 5050 5830 5800 5080 5090 3720 3730 3736 3740 3750 3900 3810 5600 8010 8020 8050 27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910 6560 7690 }
  inventions             = { 3000027 }

  policy = {
    date              = { year = 0 month = january day = 0 }
    democratic        = 5
    political_left    = 3
    freedom           = 3
    free_market       = 5
    professional_army = 2
    defense_lobby     = 3
    interventionism   = 3
  }
  headofstate            = { type = 9 id = 825089 } # Freeman Freeman-Thomas
  headofgovernment       = { type = 9 id = 825002 } # John Edward Golightly
  foreignminister        = { type = 9 id = 825003 } # Sir Jilendra Vayaphrasattar
  armamentminister       = { type = 9 id = 825004 } # Anyang Bhula
  ministerofsecurity     = { type = 9 id = 825005 } # George H. Douglas
  ministerofintelligence = { type = 9 id = 825006 } # Archibald Angus
  chiefofstaff           = { type = 9 id = 825007 } # Victor Lord Linlithgow
  chiefofarmy            = { type = 9 id = 825008 } # Arthur A. Barrett
  chiefofnavy            = { type = 9 id = 825009 } # William E. Parry
  chiefofair             = { type = 9 id = 825090 } # Cecil Bouchier

  landunit = {
    id       = { type = 12700 id = 1001 }
    name     = "Bombay District"
    location = 1517
    division = {
      id             = { type = 12700 id = 1002 }
      name           = "Mhow Area"
      type           = garrison
      model          = 3
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1003 }
    name     = "Deccan District"
    location = 1503
    division = {
      id             = { type = 12700 id = 1004 }
      name           = "4th Indian Division"
      type           = infantry
      model          = 7
      strength       = 100
    }
    division = {
      id             = { type = 12700 id = 1005 }
      name           = "4th Indian Cavalry Brigade"
      type           = cavalry
      model          = 6
      strength       = 40
    }
    division = {
      id             = { type = 12700 id = 1006 }
      name           = "Poona Area"
      type           = garrison
      model          = 3
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1007 }
    name     = "Kohat District"
    location = 1537
    division = {
      id             = { type = 12700 id = 1008 }
      name           = "Thal Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1009 }
      name           = "Kohat Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
  }
  landunit = {
    id       = { type = 12700 id = 1010 }
    name     = "Lahore District"
    location = 1530
    division = {
      id             = { type = 12700 id = 1011 }
      name           = "Sialkot Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1012 }
      name           = "Ferozepore Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1013 }
      name           = "Jullundur Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1014 }
      name           = "Lahore Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1015 }
      name           = "Ambala Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
  }
  landunit = {
    id       = { type = 12700 id = 1016 }
    name     = "Lucknow District"
    location = 1459
    division = {
      id             = { type = 12700 id = 1017 }
      name           = "Allahabad Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1018 }
      name           = "Delhi Area"
      type           = garrison
      model          = 3
      extra          = artillery
      brigade_model  = 5
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1019 }
    name     = "Madras District"
    location = 1500
    division = {
      id             = { type = 12700 id = 1020 }
      name           = "Madras Brigade"
      type           = garrison
      model          = 3
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1021 }
    name     = "Meerut District"
    location = 1460
    division = {
      id             = { type = 12700 id = 1022 }
      name           = "3rd Indian Division"
      type           = infantry
      model          = 7
      extra          = armored_car
      brigade_model  = 2
      strength       = 100
    }
    division = {
      id             = { type = 12700 id = 1023 }
      name           = "3rd Indian Cavalry Brigade"
      type           = cavalry
      model          = 6
      extra          = armored_car
      brigade_model  = 2
      strength       = 40
    }
  }
  landunit = {
    id       = { type = 12700 id = 1024 }
    name     = "Peshawar District"
    location = 1537
    division = {
      id             = { type = 12700 id = 1025 }
      name           = "Landikotal Brigade"
      type           = militia
      model          = 4
      strength       = 90
    }
    division = {
      id             = { type = 12700 id = 1026 }
      name           = "Peshawar Brigade"
      type           = militia
      model          = 4
      extra          = artillery
      brigade_model  = 5
      strength       = 90
    }
    division = {
      id             = { type = 12700 id = 1027 }
      name           = "Nowshera Brigade"
      type           = militia
      model          = 4
      strength       = 90
    }
    division = {
      id             = { type = 12700 id = 1028 }
      name           = "1st Indian Cavalry Brigade"
      type           = cavalry
      model          = 6
      strength       = 40
    }
  }
  landunit = {
    id       = { type = 12700 id = 1029 }
    name     = "Presidency & Assam District"
    location = 1447
    division = {
      id             = { type = 12700 id = 1030 }
      name           = "Eastern Bengal Brigade"
      type           = garrison
      model          = 3
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1031 }
    name     = "Rawalpindi District"
    location = 1534
    division = {
      id             = { type = 12700 id = 1032 }
      name           = "1st Indian Division"
      type           = infantry
      model          = 7
      extra          = artillery
      brigade_model  = 5
      strength       = 100
    }
  }
  landunit = {
    id       = { type = 12700 id = 1033 }
    name     = "Waziristan District"
    location = 1534
    division = {
      id             = { type = 12700 id = 1034 }
      name           = "Razmak Brigade"
      type           = militia
      model          = 4
      strength       = 90
    }
    division = {
      id             = { type = 12700 id = 1035 }
      name           = "Bannu Brigade"
      type           = militia
      model          = 4
      strength       = 90
    }
    division = {
      id             = { type = 12700 id = 1036 }
      name           = "Wana Brigade"
      type           = militia
      model          = 4
      strength       = 90
    }
  }
  landunit = {
    id       = { type = 12700 id = 1037 }
    name     = "Western District"
    location = 1529
    division = {
      id             = { type = 12700 id = 1038 }
      name           = "2nd Indian Division"
      type           = infantry
      model          = 7
      strength       = 100
    }
    division = {
      id             = { type = 12700 id = 1039 }
      name           = "Quetta Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1040 }
      name           = "Khojak Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1041 }
      name           = "Zhob Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
    division = {
      id             = { type = 12700 id = 1042 }
      name           = "Sind Brigade"
      type           = militia
      model          = 4
      strength       = 80
    }
  }
  landunit = {
    id       = { type = 12700 id = 1043 }
    name     = "Jammu & Kashmir State Forces"
    location = 1540
    division = {
      id             = { type = 12700 id = 1044 }
      name           = "Jammu Brigade"
      type           = militia
      model          = 3
      strength       = 100
      locked         = yes
    }
    division = {
      id             = { type = 12700 id = 1045 }
      name           = "Kashmir Brigade"
      type           = militia
      model          = 3
      strength       = 100
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1046 }
    name     = "Gwalior State Forces"
    location = 1523
    division = {
      id             = { type = 12700 id = 1047 }
      name           = "Gwalior Cavalry Brigade"
      type           = cavalry
      model          = 5
      strength       = 40
      locked         = yes
    }
    division = {
      id             = { type = 12700 id = 1048 }
      name           = "Gwalior Infantry Brigade"
      type           = militia
      model          = 3
      strength       = 100
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1049 }
    name     = "Hyderabad State Forces"
    location = 1487
    division = {
      id             = { type = 12700 id = 1050 }
      name           = "Hyderabad State Forces"
      type           = militia
      model          = 3
      strength       = 100
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1051 }
    name     = "Bikaner State Forces"
    location = 1527
    division = {
      id             = { type = 12700 id = 1052 }
      name           = "Bikaner State Forces"
      type           = militia
      model          = 3
      strength       = 80
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1053 }
    name     = "Patiala State Forces"
    location = 1531
    division = {
      id             = { type = 12700 id = 1054 }
      name           = "Patiala State Forces"
      type           = militia
      model          = 3
      strength       = 80
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1055 }
    name     = "Mysore State Forces"
    location = 1507
    division = {
      id             = { type = 12700 id = 1056 }
      name           = "Mysore State Forces"
      type           = militia
      model          = 3
      strength       = 70
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 12700 id = 1057 }
    name     = "Burma Command"
    location = 1415
    division = {
      id             = { type = 12700 id = 1058 }
      name           = "Rangoon Brigade"
      type           = militia
      model          = 4
      extra          = artillery
      brigade_model  = 5
      strength       = 100
    }
    division = {
      id             = { type = 12700 id = 1059 }
      name           = "Mandalay Brigade"
      type           = militia
      model          = 4
      extra          = police
      brigade_model  = 1
      strength       = 100
    }
  }

  navalunit = {
    id       = { type = 12700 id = 288 }
    name     = "Royal Indian Navy"
    location = 1517
    base     = 1517
    division = {
      id             = { type = 12700 id = 284 }
      name           = "HMIS 2nd Transport Flotilla"
      type           = transport
    }
    division = {
      id             = { type = 12700 id = 286 }
      name           = "HMIS 4th Transport Flotilla"
      type           = transport
    }
    division = {
      id             = { type = 12700 id = 2318 }
      name           = "2nd DD. Division"
      type           = destroyer
    }
    division = {
      id             = { type = 12700 id = 2319 }
      name           = "3rd DD. Division"
      type           = destroyer
    }
  }
  navalunit = {
    id       = { type = 12700 id = 2332 }
    name     = "1st Squadron"
    location = 1517
    base     = 1517
    division = {
      id             = { type = 12700 id = 289 }
      name           = "HMIS 1st Transport Flotilla"
      type           = transport
    }
    division = {
      id             = { type = 12700 id = 285 }
      name           = "HMIS 3rd Transport Flotilla"
      type           = transport
    }
    division = {
      id             = { type = 12700 id = 287 }
      name           = "HMIS Destroyer Flotilla"
      type           = destroyer
      model          = 3
    }
    division = {
      id             = { type = 12700 id = 2317 }
      name           = "1st DD. Division"
      type           = destroyer
    }
  }

  airunit = { 
    id       = { type = 12700 id = 80 }
    name     = "Royal Indian Air Force"
    location = 1517
    base     = 1517
    division = {
      id             = { type = 12700 id = 81 }
      name           = "Indian Group"
      type           = tactical_bomber
      model          = 4
      strength       = 100
    }
  }
}
