#Germany
province = { 
	id = 184 #Konigsberg
	supplypool = 10
	oilpool = 10
}
#Belgium
province = { 
	id = 894 #Matadi
	supplypool = 2
}
#China
province = { 
	id = 1296 #Guanxian
	supplypool = 1000
}
province = { 
	id = 1325 #Nanyang
	supplypool = 1000
}
#France
province = { 
	id = 728 #Oran
	supplypool = 20
}
province = { 
	id = 1002 #Tamatave
	supplypool = 2
}
#Greece
province = { 
	id = 382 #Irakleio
	supplypool = 3
}
#Italy
province = { 
	id = 435 #Sassari
	supplypool = 2
}
province = { 
	id = 765 #Tobruk
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 378 #Kalymnos
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 815 #Massawa
	supplypool = 20
	oilpool = 5
}
province = { 
	id = 836 #Mogadishu
	supplypool = 10
	oilpool = 5
}
#Japan
province = { 
	id = 1219 #Port Arthur
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 1245 #Tangshan
	supplypool = 50
	oilpool = 5
}
province = { 
	id = 1362 #Taipei
	supplypool = 2
}
province = { 
	id = 1563 #Southern Okinawa
	supplypool = 2
}
province = { 
	id = 1661 #Iwo Jima
	supplypool = 2
}
province = { 
	id = 1662 #Chichi Jima
	supplypool = 2
}
province = { 
	id = 1665 #Ponape
	supplypool = 2
}
province = { 
	id = 1667 #Truk
	supplypool = 2
}
province = { 
	id = 1670 #Peleliu
	supplypool = 2
}
province = { 
	id = 1675 #Eniwetok
	supplypool = 2
}
province = { 
	id = 1676 #Kwajalein
	supplypool = 2
}
province = { 
	id = 1685 #Saipan
	supplypool = 2
}
#Portugal
province = { 
	id = 963 #Bissau
	supplypool = 2
}
#Spain
province = { 
	id = 475 #Palma de Mallorca
	supplypool = 2
}
province = { 
	id = 715 #Tangiers
	supplypool = 5
}
province = { 
	id = 990 #Canaria
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 988 #Villa Cisneros
	supplypool = 2
}
province = { 
	id = 913 #Bata
	supplypool = 2
}
#Sweden
province = { 
	id = 2156 #Visby
	supplypool = 2
}
#United Kindgom
province = { 
	id = 348 #Gibraltar
	supplypool = 2
}
province = { 
	id = 429 #Malta
	supplypool = 2
}
province = { 
	id = 839 #Garissa
	supplypool = 2
}
province = { 
	id = 929 #Lagos
	supplypool = 2
}
province = { 
	id = 956 #Accra
	supplypool = 2
}
province = { 
	id = 1008 #Tel Aviv
	supplypool = 2
}
province = { 
	id = 1371 #Hong Kong
	supplypool = 2
}
province = { 
	id = 1432 #Singapore
	supplypool = 2
}
province = { 
	id = 1511 #Colombo
	supplypool = 2
}
province = { 
	id = 1773 #The Bermudas
	supplypool = 2
}
#USA
province = { 
	id = 889 #Balboa
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 1734 #Pearl Harbour
	supplypool = 5
	oilpool = 5
}

